support workload profiles
Azure/terraform-azure-container-apps pull request #45
Opened 2023-12-21 23:44 UTC by davidkarlsen

## Describe your changes

Support workload profiles, this is new in https://github.com/hashicorp/terraform-provider-azurerm/releases/tag/v3.85.0

## Issue number

#000

## Checklist before requesting a review
- [X] The pr title can be used to describe what this pr did in `CHANGELOG.md` file
- [ ] I have executed pre-commit on my machine
- [X] I have passed pr-check on my machine

Thanks for your cooperation!

2023-12-22 02:41 UTC, lonegunmanb commented
Hi @davidkarlsen thanks for opening this pr! I've tried `v3.85.0` provider with `startup` example, and I found that there's no configuration drift on `workload_profile_name`, it always be empty string. According to [the schema](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.85.0/internal/services/containerapps/container_app_resource.go#L110-L114), this new attribute has no default value.

2023-12-22 02:43 UTC, lonegunmanb requested changes
Thanks @davidkarlsen , one comment.

2023-12-22 02:43 UTC, lonegunmanb commented on variables.tf
> +    workload_profile_name = optional(string, "Consumption")
Could we use `optional(string)` here?

2023-12-22 10:48 UTC, davidkarlsen commented
> Hi @davidkarlsen thanks for opening this pr! I've tried `v3.85.0` provider with `startup` example, and I found that there's no configuration drift on `workload_profile_name`, it always be empty string. According to [the schema](https://github.com/hashicorp/terraform-provider-azurerm/blob/v3.85.0/internal/services/containerapps/container_app_resource.go#L110-L114), this new attribute has no default value.

Hm, probably there were some changes over time in the provider which messed it up. Let me taint the resource and re-create to test something,

2023-12-22 14:48 UTC, lonegunmanb approved these changes
Thanks @davidkarlsen , LGTM! 🚀

2023-12-22 14:48 UTC, merged

2023-12-23 00:40 UTC, davidkarlsen commented
@lonegunmanb thanks - can you create tags (and proper gh releases would be good too, as they give insights in what changes went in etc)

2023-12-25 00:11 UTC, lonegunmanb commented
@davidkarlsen We've just released a tag version. I'd like to add another feature support for this module then release our next tag.

2023-12-26 23:49 UTC, davidkarlsen commented
@lonegunmanb okidok, but releasing often and little is good as it gets out the features and helps adoption IMHO.
BTW: https://github.com/marvinpinto/action-automatic-releases can be used to automate creation of gh-releases when tagging.

2024-01-02 01:27 UTC, lonegunmanb commented
Thanks @davidkarlsen for your advice, we didn't choose automatic release due to certain considerations. We treat breaking changes very seriously, so we'd like to manage our release process manually, and keep all breaking changes in one major version upgrade.

2024-01-03 00:23 UTC, davidkarlsen commented
syre - and that's fine - it's just that:
https://github.com/Azure/terraform-azure-container-apps/releases
is off vs 
https://github.com/Azure/terraform-azure-container-apps/tags